---
name: Continuous Integration

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Postman tests
        run: newman run "JSON Placeholder.postman_collection.json" -e "JSON Placeholder Env.postman_environment.json"